import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

class AppData {

    static final Map<String, String> CAPTIONS = new HashMap<>();
    static final Map<String, String> CODE_MAP = new HashMap<>();
    private static final Map<String, String> TIME_MAP = new HashMap<>();
    private static final Map<String, String> SPACE_MAP = new HashMap<>();
    static final List<String[]> APP_DATA = new ArrayList<>();

    static {
        CAPTIONS.put("LINEAR_CHECK", "Checking arr[%d] = %s against target %s.");
        CAPTIONS.put("LINEAR_MISS", "arr[%d] = %s is not the target. Move forward.");
        CAPTIONS.put("LINEAR_FOUND", "Found it. arr[%d] = %s matches the target at index %d.");
        CAPTIONS.put("LINEAR_NOTFOUND", "Reached the end of the array. The target is not present.");
        CAPTIONS.put("BINARY_MID", "Midpoint is arr[%d] = %s. Compare it with target %s.");
        CAPTIONS.put("BINARY_LEFT", "Target is smaller, so discard the right half.");
        CAPTIONS.put("BINARY_RIGHT", "Target is larger, so discard the left half.");
        CAPTIONS.put("BINARY_FOUND", "Binary Search found the target at index %d.");
        CAPTIONS.put("TERNARY_MIDS", "Probe mid1[%d]=%s and mid2[%d]=%s to split the range into thirds.");
        CAPTIONS.put("TERNARY_LEFT", "Target is left of mid1, so keep the left third.");
        CAPTIONS.put("TERNARY_RIGHT", "Target is right of mid2, so keep the right third.");
        CAPTIONS.put("TERNARY_MID", "Target is between mid1 and mid2, so keep the middle third.");
        CAPTIONS.put("JUMP_JUMP", "Jump ahead by block size %d to index %d.");
        CAPTIONS.put("JUMP_LINEAR", "Target must be in the current block, so switch to linear scan from %d.");
        CAPTIONS.put("INTERP_POS", "Estimate the probe index from the value distribution: %d.");
        CAPTIONS.put("INTERP_LEFT", "Probe value is smaller than the target. Shift right.");
        CAPTIONS.put("INTERP_RIGHT", "Probe value is larger than the target. Shift left.");
        CAPTIONS.put("EXP_BOUND", "Doubling the bound to %d to locate a useful search range.");
        CAPTIONS.put("EXP_BINARY", "Range located: [%d, %d]. Switch to binary search inside it.");
        CAPTIONS.put("FIB_PROBE", "Fibonacci probe at index %d using fibM2 = %d.");
        CAPTIONS.put("FIB_LEFT", "Probe value is too large. Reduce the Fibonacci window to the left.");
        CAPTIONS.put("FIB_RIGHT", "Probe value is too small. Shift the Fibonacci window right.");
        CAPTIONS.put("GRAPH_VISIT", "Visiting node '%s'. Is it the target '%s'?");
        CAPTIONS.put("GRAPH_ENQUEUE", "Queueing the neighbors of '%s': %s");
        CAPTIONS.put("GRAPH_PUSH", "Pushing the neighbors of '%s' onto the stack: %s");
        CAPTIONS.put("GRAPH_PATH", "Target found. Reconstructed path: %s");
        CAPTIONS.put("KMP_MATCH", "text[%d]='%s' matches pattern[%d]='%s'. Advance both pointers.");
        CAPTIONS.put("KMP_MISMATCH", "Mismatch at text[%d]. Fall back in the pattern to LPS position %d.");
        CAPTIONS.put("KMP_FOUND", "Full pattern match found at text position %d.");
        CAPTIONS.put("RK_WINDOW", "Rolling hash window at position %d.");
        CAPTIONS.put("RK_HASHMATCH", "Hash match at position %d. Verify characters directly.");
        CAPTIONS.put("RK_FOUND", "Confirmed substring match at position %d.");

        CODE_MAP.put("Linear Search", lines(
            "// ─── LINEAR SEARCH ───────────────────────────────────────────────",
            "// The simplest search algorithm: go through the array one element at",
            "// a time from left to right, and stop as soon as we find the target.",
            "//",
            "// No sorting required — works on any array in any order.",
            "// Returns the INDEX where the target was found, or -1 if it isn't there.",
            "// ─────────────────────────────────────────────────────────────────",
            "public int linearSearch(int[] arr, int target) {",
            "",
            "    // i is our position in the array — start at the beginning (index 0)",
            "    for (int i = 0; i < arr.length; i++) {",
            "",
            "        // Check if the element at the current position matches our target",
            "        if (arr[i] == target) {",
            "            return i;  // Found it! Return its index immediately",
            "        }",
            "        // If not, the loop moves i forward and checks the next element",
            "    }",
            "",
            "    // If we finish the loop without finding the target, it isn't in the array",
            "    return -1;",
            "}"
        ));
        CODE_MAP.put("Binary Search", lines(
            "// ─── BINARY SEARCH ───────────────────────────────────────────────",
            "// Instead of checking every element, we start in the MIDDLE of the",
            "// array and ask: is the target smaller or larger than the midpoint?",
            "// That one question cuts the remaining search area in HALF each time.",
            "//",
            "// REQUIREMENT: the array must be sorted in ascending order first.",
            "// Returns the index of the target, or -1 if not found.",
            "// ─────────────────────────────────────────────────────────────────",
            "public int binarySearch(int[] arr, int target) {",
            "",
            "    // 'low' and 'high' mark the boundaries of where the target could be.",
            "    // We start by considering the entire array.",
            "    int low  = 0;",
            "    int high = arr.length - 1;",
            "",
            "    // Keep searching as long as there is still a valid range to look in",
            "    while (low <= high) {",
            "",
            "        // Find the middle index of the current range.",
            "        // We write it this way (instead of (low+high)/2) to avoid",
            "        // an integer overflow bug when low and high are very large.",
            "        int mid = low + (high - low) / 2;",
            "",
            "        if (arr[mid] == target) {",
            "            return mid;  // Bullseye — target is exactly at the midpoint",
            "        }",
            "",
            "        if (arr[mid] < target) {",
            "            // The midpoint is too small, so the target must be to the RIGHT.",
            "            // Discard everything on the left by moving 'low' up.",
            "            low = mid + 1;",
            "        } else {",
            "            // The midpoint is too large, so the target must be to the LEFT.",
            "            // Discard everything on the right by moving 'high' down.",
            "            high = mid - 1;",
            "        }",
            "    }",
            "",
            "    // The search range collapsed to nothing — target is not in the array",
            "    return -1;",
            "}"
        ));
        CODE_MAP.put("Ternary Search", lines(
            "// ─── TERNARY SEARCH ──────────────────────────────────────────────",
            "// Similar to Binary Search, but instead of splitting the range in two,",
            "// we split it into THREE equal parts using two probe points: mid1 and mid2.",
            "// Each step eliminates one third of the remaining range.",
            "//",
            "// REQUIREMENT: the array must be sorted in ascending order.",
            "// Returns the index of the target, or -1 if not found.",
            "// ─────────────────────────────────────────────────────────────────",
            "public int ternarySearch(int[] arr, int target) {",
            "",
            "    int low  = 0;",
            "    int high = arr.length - 1;",
            "",
            "    while (low <= high) {",
            "",
            "        // Divide the current range into three equal sections.",
            "        // mid1 is one-third of the way in from the left.",
            "        // mid2 is one-third of the way in from the right.",
            "        int third = (high - low) / 3;",
            "        int mid1  = low + third;",
            "        int mid2  = high - third;",
            "",
            "        // Check if either probe point is the target",
            "        if (arr[mid1] == target) return mid1;",
            "        if (arr[mid2] == target) return mid2;",
            "",
            "        if (target < arr[mid1]) {",
            "            // Target is smaller than mid1 — it must be in the LEFT third.",
            "            // Discard the middle and right thirds.",
            "            high = mid1 - 1;",
            "        } else if (target > arr[mid2]) {",
            "            // Target is larger than mid2 — it must be in the RIGHT third.",
            "            // Discard the left and middle thirds.",
            "            low = mid2 + 1;",
            "        } else {",
            "            // Target is between mid1 and mid2 — it's in the MIDDLE third.",
            "            // Discard the left and right thirds.",
            "            low  = mid1 + 1;",
            "            high = mid2 - 1;",
            "        }",
            "    }",
            "",
            "    return -1;  // Target not found",
            "}"
        ));
        CODE_MAP.put("Jump Search", lines(
            "// ─── JUMP SEARCH ─────────────────────────────────────────────────",
            "// Instead of checking every element (like Linear Search), we JUMP",
            "// forward in fixed-size blocks until we overshoot the target.",
            "// Then we step back one block and do a small linear scan.",
            "//",
            "// The ideal block size is √n (square root of the array length).",
            "// This balances the number of jumps with the size of the final scan.",
            "//",
            "// REQUIREMENT: the array must be sorted in ascending order.",
            "// Returns the index of the target, or -1 if not found.",
            "// ─────────────────────────────────────────────────────────────────",
            "public int jumpSearch(int[] arr, int target) {",
            "",
            "    int n    = arr.length;",
            "    int step = (int) Math.sqrt(n);  // block size — the optimal jump distance",
            "    int prev = 0;                    // the start of the current block",
            "",
            "    // ── Phase 1: Jump forward block by block ──────────────────────",
            "    // Keep jumping until arr[step] is >= target, or we reach the end.",
            "    // When we stop, the target (if present) is in the block [prev, step).",
            "    while (step < n && arr[step] < target) {",
            "        prev  = step;        // remember where this block started",
            "        step += (int) Math.sqrt(n);  // jump forward by one block",
            "    }",
            "",
            "    // ── Phase 2: Linear scan within the identified block ──────────",
            "    // We now know the target is somewhere between 'prev' and 'step'.",
            "    // Check each element in that small range one by one.",
            "    for (int i = prev; i < Math.min(step, n); i++) {",
            "        if (arr[i] == target) {",
            "            return i;  // Found it!",
            "        }",
            "    }",
            "",
            "    return -1;  // Target not found in the array",
            "}"
        ));
        CODE_MAP.put("Interpolation Search", lines(
            "// ─── INTERPOLATION SEARCH ────────────────────────────────────────",
            "// Binary Search always checks the midpoint. Interpolation Search is",
            "// smarter — it ESTIMATES where the target likely is based on its value.",
            "//",
            "// Think of looking up a name in a phone book: you don't open it to the",
            "// middle to find 'Smith' — you open it near the end because S is late",
            "// in the alphabet. That proportional estimate is exactly what this does.",
            "//",
            "// Works best when values are UNIFORMLY distributed (evenly spread).",
            "// REQUIREMENT: the array must be sorted in ascending order.",
            "// Returns the index of the target, or -1 if not found.",
            "// ─────────────────────────────────────────────────────────────────",
            "public int interpolationSearch(int[] arr, int target) {",
            "",
            "    int low  = 0;",
            "    int high = arr.length - 1;",
            "",
            "    // Continue only while there's a valid range AND the target is within it.",
            "    // If target < arr[low] or target > arr[high], it cannot be in the array.",
            "    while (low <= high && target >= arr[low] && target <= arr[high]) {",
            "",
            "        // Edge case: the range has collapsed to a single element",
            "        if (low == high) {",
            "            if (arr[low] == target) return low;",
            "            return -1;",
            "        }",
            "",
            "        // ── The key formula: estimate the probe position ──────────",
            "        // We ask: if the values were spread out evenly from arr[low]",
            "        // to arr[high], whereabouts would 'target' fall in that range?",
            "        //",
            "        //   pos = low + (target - arr[low])   × (high - low)",
            "        //                ─────────────────",
            "        //               (arr[high] - arr[low])",
            "        //",
            "        // The fraction (target-arr[low]) / (arr[high]-arr[low])",
            "        // is a value between 0.0 and 1.0 representing how far 'target'",
            "        // sits between the smallest and largest values in the range.",
            "        int pos = low + (int) (((double)(target - arr[low])",
            "                  / (arr[high] - arr[low])) * (high - low));",
            "",
            "        if (arr[pos] == target) return pos;  // Direct hit!",
            "",
            "        if (arr[pos] < target) {",
            "            // Our probe was too small — target is further to the right",
            "            low = pos + 1;",
            "        } else {",
            "            // Our probe was too large — target is further to the left",
            "            high = pos - 1;",
            "        }",
            "    }",
            "",
            "    return -1;  // Target not found",
            "}"
        ));
        CODE_MAP.put("Exponential Search", lines(
            "// ─── EXPONENTIAL SEARCH ──────────────────────────────────────────",
            "// Works in two phases:",
            "//   Phase 1 — FIND THE RANGE: start at index 1 and keep doubling",
            "//             (1 → 2 → 4 → 8 → 16 ...) until we find an element",
            "//             that is >= the target. Now we know the target lives",
            "//             somewhere in the range [bound/2, bound].",
            "//   Phase 2 — SEARCH THE RANGE: run Binary Search on that small range.",
            "//",
            "// Especially useful when the array is very large or its size is unknown.",
            "// REQUIREMENT: the array must be sorted in ascending order.",
            "// Returns the index of the target, or -1 if not found.",
            "// ─────────────────────────────────────────────────────────────────",
            "public int exponentialSearch(int[] arr, int target) {",
            "",
            "    // Quick check: is the target right at the very beginning?",
            "    if (arr[0] == target) return 0;",
            "",
            "    // ── Phase 1: Double the bound until we overshoot the target ───",
            "    int bound = 1;  // start at index 1",
            "    while (bound < arr.length && arr[bound] <= target) {",
            "        bound *= 2;  // double: 1, 2, 4, 8, 16 ...",
            "    }",
            "    // At this point, arr[bound/2] < target <= arr[bound] (if bound < length).",
            "    // So the target must be somewhere in [bound/2, bound].",
            "",
            "    // ── Phase 2: Binary Search within that found range ────────────",
            "    int low  = bound / 2;                          // left boundary of range",
            "    int high = Math.min(bound, arr.length - 1);   // right boundary (clamp to array end)",
            "",
            "    while (low <= high) {",
            "        int mid = low + (high - low) / 2;",
            "        if (arr[mid] == target) return mid;   // Found it!",
            "        if (arr[mid] < target)  low  = mid + 1;  // target is to the right",
            "        else                    high = mid - 1;  // target is to the left",
            "    }",
            "",
            "    return -1;  // Target not found",
            "}"
        ));
        CODE_MAP.put("Fibonacci Search", lines(
            "// ─── FIBONACCI SEARCH ────────────────────────────────────────────",
            "// Like Binary Search, but uses Fibonacci numbers to decide where to",
            "// probe instead of dividing by 2. This avoids division entirely,",
            "// which can be useful on hardware where division is slow.",
            "//",
            "// The three Fibonacci variables (fibM2, fibM1, fib) represent three",
            "// consecutive Fibonacci numbers. We shrink them each step to narrow",
            "// the search range.",
            "//",
            "// REQUIREMENT: the array must be sorted in ascending order.",
            "// Returns the index of the target, or -1 if not found.",
            "// ─────────────────────────────────────────────────────────────────",
            "public int fibonacciSearch(int[] arr, int target) {",
            "",
            "    int n = arr.length;",
            "",
            "    // ── Step 1: Find the smallest Fibonacci number >= n ──────────",
            "    // fibM2, fibM1, fib are three consecutive Fibonacci numbers.",
            "    // Example sequence: 0, 1, 1, 2, 3, 5, 8, 13, 21 ...",
            "    int fibM2 = 0;  // fib(k-2)",
            "    int fibM1 = 1;  // fib(k-1)",
            "    int fib   = 1;  // fib(k)   — starts as fib(2) = 1",
            "    while (fib < n) {",
            "        fibM2 = fibM1;",
            "        fibM1 = fib;",
            "        fib   = fibM1 + fibM2;  // next Fibonacci number",
            "    }",
            "",
            "    // 'offset' is the left boundary of the part of the array we haven't",
            "    // eliminated yet. -1 means we haven't eliminated anything yet.",
            "    int offset = -1;",
            "",
            "    // ── Step 2: Shrink the Fibonacci window until we find the target ──",
            "    while (fib > 1) {",
            "",
            "        // Calculate the probe index.",
            "        // offset + fibM2 gives us a position fibM2 steps ahead of 'offset'.",
            "        // Math.min(..., n-1) makes sure we don't go past the end of the array.",
            "        int i = Math.min(offset + fibM2, n - 1);",
            "",
            "        if (arr[i] < target) {",
            "            // The probe is too small — eliminate everything to the LEFT.",
            "            // Move the window right by stepping down one Fibonacci level.",
            "            fib   = fibM1;",
            "            fibM1 = fibM2;",
            "            fibM2 = fib - fibM1;",
            "            offset = i;  // the new left boundary is the probe we just checked",
            "        } else if (arr[i] > target) {",
            "            // The probe is too large — eliminate everything to the RIGHT.",
            "            // Shrink the window by stepping down two Fibonacci levels.",
            "            fib   = fibM2;",
            "            fibM1 -= fibM2;",
            "            fibM2 = fib - fibM1;",
            "        } else {",
            "            return i;  // Exact match — return the index",
            "        }",
            "    }",
            "",
            "    // ── Step 3: Check the final remaining candidate element ───────",
            "    // When fib reaches 1, there is exactly one element left to check.",
            "    if (fibM1 == 1 && offset + 1 < n && arr[offset + 1] == target) {",
            "        return offset + 1;",
            "    }",
            "",
            "    return -1;  // Target not found",
            "}"
        ));
        CODE_MAP.put("Breadth-First Search", lines(
            "// ─── BREADTH-FIRST SEARCH (BFS) ──────────────────────────────────",
            "// BFS explores a graph LEVEL BY LEVEL — like ripples spreading out",
            "// from a stone dropped in water. It visits all nodes at distance 1",
            "// before any node at distance 2, and so on.",
            "//",
            "// Because of this, BFS always finds the SHORTEST path (fewest hops)",
            "// in an unweighted graph.",
            "//",
            "// Key data structures:",
            "//   queue   — nodes waiting to be explored (FIFO: first in, first out)",
            "//   visited — nodes we've already seen (so we don't revisit them)",
            "//   parent  — records which node we came from (so we can retrace the path)",
            "// ─────────────────────────────────────────────────────────────────",
            "public List<String> bfs(Map<String, List<String>> graph,",
            "                        String start, String target) {",
            "",
            "    Queue<String> queue        = new LinkedList<>();  // nodes to explore next",
            "    Set<String> visited        = new HashSet<>();      // nodes already seen",
            "    Map<String, String> parent = new HashMap<>();     // node → who we came from",
            "",
            "    // Begin at the start node",
            "    queue.add(start);",
            "    visited.add(start);",
            "    parent.put(start, null);  // the start has no parent",
            "",
            "    while (!queue.isEmpty()) {",
            "",
            "        // Take the next node from the FRONT of the queue (oldest first)",
            "        String node = queue.poll();",
            "",
            "        // Check if this is the node we're looking for",
            "        if (node.equals(target)) {",
            "            return buildPath(parent, node);  // trace back the path and return it",
            "        }",
            "",
            "        // Add all unvisited neighbors to the queue for future exploration",
            "        for (String neighbor : graph.getOrDefault(node, List.of())) {",
            "            if (visited.add(neighbor)) {  // .add() returns false if already present",
            "                parent.put(neighbor, node);  // remember we came from 'node'",
            "                queue.add(neighbor);",
            "            }",
            "        }",
            "    }",
            "",
            "    return List.of();  // We exhausted all reachable nodes — target not found",
            "}",
            "",
            "// ── Helper: Reconstruct the path from start to the target node ───",
            "// We follow the 'parent' map backwards from the target to the start,",
            "// then reverse the result so it reads start → ... → target.",
            "private List<String> buildPath(Map<String, String> parent, String node) {",
            "    List<String> path = new ArrayList<>();",
            "    // Walk backwards: from target, follow parent pointers until we reach start",
            "    for (String current = node; current != null; current = parent.get(current)) {",
            "        path.add(0, current);  // prepend so the list ends up in forward order",
            "    }",
            "    return path;",
            "}"
        ));
        CODE_MAP.put("Depth-First Search", lines(
            "// ─── DEPTH-FIRST SEARCH (DFS) ────────────────────────────────────",
            "// DFS dives as DEEP as possible down one path before backtracking.",
            "// Think of exploring a maze: you follow one corridor all the way to",
            "// its end, then turn back and try the next corridor.",
            "//",
            "// Unlike BFS, DFS does NOT guarantee the shortest path.",
            "// But it uses less memory on wide graphs and is great for tasks like",
            "// cycle detection, dependency resolution, and maze solving.",
            "//",
            "// Key data structures:",
            "//   stack   — nodes to explore next (LIFO: last in, first out)",
            "//             This gives DFS its 'go deep first' behavior.",
            "//   visited — nodes already processed (prevents infinite loops)",
            "//   parent  — records the path so we can retrace it",
            "// ─────────────────────────────────────────────────────────────────",
            "public List<String> dfs(Map<String, List<String>> graph,",
            "                        String start, String target) {",
            "",
            "    Deque<String> stack        = new ArrayDeque<>();  // our exploration stack",
            "    Set<String> visited        = new HashSet<>();      // already-processed nodes",
            "    Map<String, String> parent = new HashMap<>();      // node → who we came from",
            "",
            "    // Begin at the start node",
            "    stack.push(start);",
            "    parent.put(start, null);  // the start has no parent",
            "",
            "    while (!stack.isEmpty()) {",
            "",
            "        // Take the node from the TOP of the stack (most recently added)",
            "        String node = stack.pop();",
            "",
            "        // Skip this node if we've already fully processed it",
            "        if (!visited.add(node)) continue;  // .add() returns false if already present",
            "",
            "        // Check if this is the node we're looking for",
            "        if (node.equals(target)) {",
            "            return buildPath(parent, node);  // trace back the path and return it",
            "        }",
            "",
            "        // Push neighbors in REVERSE order so the first neighbor",
            "        // ends up on top of the stack and gets processed first.",
            "        List<String> neighbors = graph.getOrDefault(node, List.of());",
            "        for (int i = neighbors.size() - 1; i >= 0; i--) {",
            "            String neighbor = neighbors.get(i);",
            "            if (!visited.contains(neighbor)) {",
            "                parent.putIfAbsent(neighbor, node);  // record how we got here",
            "                stack.push(neighbor);",
            "            }",
            "        }",
            "    }",
            "",
            "    return List.of();  // We exhausted all reachable nodes — target not found",
            "}",
            "",
            "// ── Helper: Reconstruct the path from start to the target node ───",
            "// We follow the 'parent' map backwards from the target to the start,",
            "// then reverse the result so it reads start → ... → target.",
            "private List<String> buildPath(Map<String, String> parent, String node) {",
            "    List<String> path = new ArrayList<>();",
            "    for (String current = node; current != null; current = parent.get(current)) {",
            "        path.add(0, current);  // prepend so the list ends up in forward order",
            "    }",
            "    return path;",
            "}"
        ));
        CODE_MAP.put("KMP Search", lines(
            "// ─── KMP SEARCH (Knuth-Morris-Pratt) ────────────────────────────",
            "// A naive string search re-checks characters we already know about",
            "// after a mismatch. KMP avoids this by precomputing an LPS table.",
            "//",
            "// LPS = Longest Proper Prefix that is also a Suffix.",
            "// Example: for pattern \"ABABC\", lps = [0, 0, 1, 2, 0]",
            "//   lps[3] = 2 because \"ABAB\"'s longest prefix-suffix is \"AB\" (length 2).",
            "// When a mismatch occurs, lps tells us how far back to jump in the",
            "// pattern without moving backwards in the text.",
            "//",
            "// Returns a list of all starting positions where pattern appears in text.",
            "// ─────────────────────────────────────────────────────────────────",
            "public List<Integer> kmpSearch(String text, String pattern) {",
            "",
            "    int[] lps = buildLPS(pattern);      // precompute the failure function",
            "    List<Integer> matches = new ArrayList<>();",
            "",
            "    int i = 0;  // position in 'text'    — never goes backwards",
            "    int j = 0;  // position in 'pattern' — can jump back using lps",
            "",
            "    while (i < text.length()) {",
            "",
            "        if (text.charAt(i) == pattern.charAt(j)) {",
            "            // Characters match — advance both pointers",
            "            i++;",
            "            j++;",
            "",
            "            if (j == pattern.length()) {",
            "                // j has reached the end of the pattern — full match found!",
            "                matches.add(i - j);   // the match starts at index (i - j)",
            "                // Use lps to look for the next overlapping match",
            "                j = lps[j - 1];",
            "            }",
            "        } else if (j > 0) {",
            "            // Mismatch, but we've matched some characters already.",
            "            // Don't move 'i' — just jump 'j' back using the LPS table.",
            "            // This reuses the longest suffix of what we've matched so far",
            "            // that is also a valid prefix of the pattern.",
            "            j = lps[j - 1];",
            "        } else {",
            "            // Mismatch at the very start of the pattern — just move 'i' forward",
            "            i++;",
            "        }",
            "    }",
            "",
            "    return matches;",
            "}",
            "",
            "// ── Helper: Build the LPS (failure function) table ───────────────",
            "// lps[i] = the length of the longest proper prefix of pattern[0..i]",
            "//          that is also a suffix of pattern[0..i].",
            "// 'Proper' means the prefix cannot be the entire string itself.",
            "//",
            "// Example: pattern = \"ABABC\"",
            "//   i=0  'A'     → lps[0] = 0  (by definition, always 0)",
            "//   i=1  'AB'    → lps[1] = 0  (no matching prefix-suffix)",
            "//   i=2  'ABA'   → lps[2] = 1  ('A' is both a prefix and suffix)",
            "//   i=3  'ABAB'  → lps[3] = 2  ('AB' is both a prefix and suffix)",
            "//   i=4  'ABABC' → lps[4] = 0  (no matching prefix-suffix)",
            "private int[] buildLPS(String pattern) {",
            "",
            "    int   m   = pattern.length();",
            "    int[] lps = new int[m];",
            "    int   len = 0;  // length of the current matching prefix-suffix",
            "    int   i   = 1;  // we start at index 1 (lps[0] is always 0)",
            "    lps[0]    = 0;",
            "",
            "    while (i < m) {",
            "        if (pattern.charAt(i) == pattern.charAt(len)) {",
            "            // The prefix ending at 'len' and the suffix ending at 'i' match.",
            "            // Extend the current prefix-suffix by one character.",
            "            lps[i] = ++len;",
            "            i++;",
            "        } else if (len > 0) {",
            "            // Mismatch — try a shorter prefix-suffix using the table itself.",
            "            // This is the same 'smart fallback' idea as in the search above.",
            "            len = lps[len - 1];",
            "        } else {",
            "            // No prefix-suffix of any length matches — record 0 and move on.",
            "            lps[i] = 0;",
            "            i++;",
            "        }",
            "    }",
            "    return lps;",
            "}"
        ));
        CODE_MAP.put("Rabin-Karp Search", lines(
            "// ─── RABIN-KARP SEARCH ───────────────────────────────────────────",
            "// Instead of comparing every character of the pattern at every position,",
            "// Rabin-Karp computes a HASH (a numeric fingerprint) of the pattern and",
            "// slides a same-size window across the text, comparing hashes.",
            "//",
            "// If the hashes match, we do a character-by-character check to confirm",
            "// (because different strings can sometimes produce the same hash — a",
            "// 'collision'). If they don't match, we move on instantly.",
            "//",
            "// The key trick is the ROLLING HASH: instead of recomputing the entire",
            "// window hash each step (expensive), we drop the leftmost character and",
            "// add the new rightmost character in O(1) time.",
            "// ─────────────────────────────────────────────────────────────────",
            "",
            "// BASE and MOD are constants used in the hash formula.",
            "// BASE maps each character to a unique weight.",
            "// MOD keeps numbers from growing too large (modular arithmetic).",
            "private static final long BASE = 31;",
            "private static final long MOD  = 1_000_000_007L;",
            "",
            "public List<Integer> rabinKarp(String text, String pattern) {",
            "",
            "    int n = text.length();",
            "    int m = pattern.length();",
            "    List<Integer> matches = new ArrayList<>();",
            "    if (m > n) return matches;  // pattern can't fit — return empty list",
            "",
            "    long patHash = computeHash(pattern, m);  // fingerprint of the pattern",
            "    long winHash = computeHash(text, m);     // fingerprint of the first window",
            "    long power   = computePower(m);  // BASE^(m-1) mod MOD — needed for rolling",
            "",
            "    // Check position 0 before the loop starts",
            "    if (winHash == patHash && verify(text, pattern, 0)) matches.add(0);",
            "",
            "    // Slide the window one character to the right at each step",
            "    for (int i = 1; i <= n - m; i++) {",
            "",
            "        // ── Roll the hash ──────────────────────────────────────────",
            "        // Step 1: Subtract the contribution of the character leaving the window",
            "        //         (the leftmost character, at index i-1)",
            "        winHash = (winHash - charVal(text.charAt(i - 1)) * power % MOD + MOD) % MOD;",
            "",
            "        // Step 2: Shift everything left (multiply by BASE), then",
            "        //         add the new character entering from the right (at index i+m-1)",
            "        winHash = (winHash * BASE + charVal(text.charAt(i + m - 1))) % MOD;",
            "",
            "        // If hashes match, verify character by character to rule out collisions",
            "        if (winHash == patHash && verify(text, pattern, i)) matches.add(i);",
            "    }",
            "",
            "    return matches;",
            "}",
            "",
            "// ── Helper: Compute the hash for the first 'len' characters of s ─",
            "// Uses polynomial hashing: hash = c[0]*BASE^(len-1) + c[1]*BASE^(len-2) + ...",
            "// We take everything mod MOD to keep numbers manageable.",
            "private long computeHash(String s, int len) {",
            "    long hash = 0;",
            "    for (int i = 0; i < len; i++) {",
            "        hash = (hash * BASE + charVal(s.charAt(i))) % MOD;",
            "    }",
            "    return hash;",
            "}",
            "",
            "// ── Helper: Compute BASE^(len-1) mod MOD ─────────────────────────",
            "// This is the 'weight' of the leftmost character in the window.",
            "// We need it to remove that character's contribution when rolling.",
            "private long computePower(int len) {",
            "    long power = 1;",
            "    for (int i = 0; i < len - 1; i++) power = (power * BASE) % MOD;",
            "    return power;",
            "}",
            "",
            "// ── Helper: Map a character to a positive number (a=1, b=2, ...) ─",
            "// This ensures every character has a unique non-zero numeric value.",
            "private long charVal(char c) {",
            "    return Character.toLowerCase(c) - 'a' + 1;",
            "}",
            "",
            "// ── Helper: Confirm a hash match by comparing characters directly ─",
            "// Guards against hash collisions (two different strings with the same hash).",
            "private boolean verify(String text, String pattern, int start) {",
            "    for (int i = 0; i < pattern.length(); i++) {",
            "        if (text.charAt(start + i) != pattern.charAt(i)) return false;",
            "    }",
            "    return true;",
            "}"
        ));
        CODE_MAP.put("Bubble Sort", lines(
            "// ─── BUBBLE SORT ─────────────────────────────────────────────────",
            "// On each pass through the array, we compare neighbouring pairs of",
            "// elements and swap them if they are in the wrong order.",
            "// The largest unsorted element 'bubbles' all the way to its correct",
            "// position at the end of the array on each pass.",
            "//",
            "// After pass 1: the largest element is in its final position.",
            "// After pass 2: the 2nd largest is in its final position. And so on.",
            "//",
            "// The 'swapped' flag is an optimisation: if we complete an entire pass",
            "// without swapping anything, the array is already sorted and we stop early.",
            "// ─────────────────────────────────────────────────────────────────",
            "public void bubbleSort(int[] arr) {",
            "",
            "    int n = arr.length;",
            "",
            "    // Outer loop: each iteration i locks one more element at the end",
            "    for (int i = 0; i < n - 1; i++) {",
            "",
            "        boolean swapped = false;  // track whether any swap happened this pass",
            "",
            "        // Inner loop: compare adjacent pairs up to the already-sorted region.",
            "        // We go up to n-i-1 because the last i elements are already sorted.",
            "        for (int j = 0; j < n - i - 1; j++) {",
            "",
            "            if (arr[j] > arr[j + 1]) {",
            "                // These two neighbours are in the wrong order — swap them",
            "                int temp    = arr[j];",
            "                arr[j]      = arr[j + 1];",
            "                arr[j + 1]  = temp;",
            "                swapped = true;",
            "            }",
            "        }",
            "",
            "        // arr[n-i-1] is now the largest in the unsorted region — it's locked",
            "",
            "        // Early exit: if nothing was swapped, the array is already sorted",
            "        if (!swapped) break;",
            "    }",
            "}"
        ));
        CODE_MAP.put("Insertion Sort", lines(
            "// ─── INSERTION SORT ──────────────────────────────────────────────",
            "// Think of sorting a hand of playing cards: you pick up one card at",
            "// a time and slide it into the correct position among the cards you",
            "// already hold. Insertion Sort does exactly that.",
            "//",
            "// The array is divided into two regions:",
            "//   LEFT  — arr[0..i-1]: already sorted (grows each iteration)",
            "//   RIGHT — arr[i..n-1]: not yet sorted  (shrinks each iteration)",
            "//",
            "// We pick arr[i] (called 'key'), shift all sorted elements that are",
            "// larger than 'key' one step to the right, then drop 'key' into the gap.",
            "// ─────────────────────────────────────────────────────────────────",
            "public void insertionSort(int[] arr) {",
            "",
            "    // Start from index 1 because a single element (index 0) is trivially sorted",
            "    for (int i = 1; i < arr.length; i++) {",
            "",
            "        int key = arr[i];  // the element we're going to insert into sorted region",
            "        int j   = i - 1;  // start comparing from the element just to the left",
            "",
            "        // Shift all sorted elements that are greater than 'key' one position right.",
            "        // This opens up a gap for 'key' to be inserted.",
            "        while (j >= 0 && arr[j] > key) {",
            "            arr[j + 1] = arr[j];  // move this element one step to the right",
            "            j--;                  // check the next element to the left",
            "        }",
            "",
            "        // 'j' now points to the last element that is <= key (or -1 if none).",
            "        // The correct position for 'key' is the slot just to its right.",
            "        arr[j + 1] = key;",
            "    }",
            "}"
        ));
        CODE_MAP.put("Selection Sort", lines(
            "// ─── SELECTION SORT ──────────────────────────────────────────────",
            "// On each pass, we SCAN the entire unsorted portion of the array to",
            "// find the smallest element, then SWAP it into its correct position",
            "// at the left edge of the unsorted region.",
            "//",
            "// The array is divided into two regions:",
            "//   LEFT  — arr[0..i-1]: already sorted (grows each iteration)",
            "//   RIGHT — arr[i..n-1]: unsorted        (shrinks each iteration)",
            "//",
            "// Selection Sort does the fewest swaps of any simple sorting algorithm",
            "// (at most n-1), but it always does O(n^2) comparisons.",
            "// ─────────────────────────────────────────────────────────────────",
            "public void selectionSort(int[] arr) {",
            "",
            "    int n = arr.length;",
            "",
            "    // Each iteration of the outer loop places one element into its final position",
            "    for (int i = 0; i < n - 1; i++) {",
            "",
            "        // Assume the first element of the unsorted region is the smallest",
            "        int minIndex = i;",
            "",
            "        // Scan the rest of the unsorted region for a smaller element",
            "        for (int j = i + 1; j < n; j++) {",
            "            if (arr[j] < arr[minIndex]) {",
            "                minIndex = j;  // found a new minimum — update its index",
            "            }",
            "        }",
            "",
            "        // Swap the found minimum into position i",
            "        // (only swap if minIndex actually changed — i.e. it wasn't already i)",
            "        int temp       = arr[i];",
            "        arr[i]         = arr[minIndex];",
            "        arr[minIndex]  = temp;",
            "",
            "        // arr[0..i] is now sorted and will never be touched again",
            "    }",
            "}"
        ));
        CODE_MAP.put("Gnome Sort", lines(
            "// ─── GNOME SORT ──────────────────────────────────────────────────",
            "// Imagine a garden gnome sorting flower pots. He walks along the row:",
            "//   - If the current pot is in the right order vs the one behind it,",
            "//     he takes a step forward.",
            "//   - If they're in the wrong order, he swaps them and steps backward",
            "//     to re-check the pair behind him (like Bubble Sort, but one at a time).",
            "//   - If he's at the very beginning (position 0), he can only go forward.",
            "//",
            "// Simple to understand, but O(n^2) — mostly used for learning purposes.",
            "// ─────────────────────────────────────────────────────────────────",
            "public void gnomeSort(int[] arr) {",
            "",
            "    int position = 0;  // the gnome's current index in the array",
            "",
            "    while (position < arr.length) {",
            "",
            "        if (position == 0) {",
            "            // At the start — nowhere to step back, so always move forward",
            "            position++;",
            "            continue;",
            "        }",
            "",
            "        if (arr[position] >= arr[position - 1]) {",
            "            // The current element is >= the one behind it — correct order.",
            "            // The gnome is happy and moves forward.",
            "            position++;",
            "        } else {",
            "            // The current element is smaller than the one behind it — wrong order!",
            "            // Swap them to fix it, then step back to re-check.",
            "            int temp              = arr[position];",
            "            arr[position]         = arr[position - 1];",
            "            arr[position - 1]     = temp;",
            "            position--;  // step back to check the newly swapped pair",
            "        }",
            "    }",
            "}"
        ));
        CODE_MAP.put("Merge Sort", lines(
            "// ─── MERGE SORT ──────────────────────────────────────────────────",
            "// Follows the 'divide and conquer' strategy:",
            "//   1. DIVIDE  — Split the array in half (recursively) until each",
            "//                piece contains just one element. A single element",
            "//                is trivially sorted.",
            "//   2. CONQUER — Merge pairs of sorted pieces back together, always",
            "//                combining them in sorted order.",
            "//",
            "// Merge Sort is STABLE (equal elements keep their original order),",
            "// always O(n log n), but needs O(n) extra memory for the temporary arrays.",
            "// ─────────────────────────────────────────────────────────────────",
            "public void mergeSort(int[] arr, int left, int right) {",
            "",
            "    // Base case: a range of 0 or 1 element is already sorted — stop here",
            "    if (left >= right) return;",
            "",
            "    // Find the midpoint to split the current range in half",
            "    int mid = (left + right) / 2;",
            "",
            "    mergeSort(arr, left, mid);       // recursively sort the LEFT half",
            "    mergeSort(arr, mid + 1, right);  // recursively sort the RIGHT half",
            "    merge(arr, left, mid, right);    // merge the two sorted halves together",
            "}",
            "",
            "// ── Helper: Merge two sorted halves into a single sorted section ─",
            "// arr[left..mid] and arr[mid+1..right] are both already sorted.",
            "// We copy them into temporary arrays, then write back the elements",
            "// in sorted order.",
            "private void merge(int[] arr, int left, int mid, int right) {",
            "",
            "    // Copy each half into a temporary array",
            "    int[] leftHalf  = Arrays.copyOfRange(arr, left,    mid + 1);",
            "    int[] rightHalf = Arrays.copyOfRange(arr, mid + 1, right + 1);",
            "",
            "    int i = 0;     // pointer into leftHalf",
            "    int j = 0;     // pointer into rightHalf",
            "    int k = left;  // write position back into arr",
            "",
            "    // Compare the front of each half and pick the smaller one",
            "    while (i < leftHalf.length && j < rightHalf.length) {",
            "        if (leftHalf[i] <= rightHalf[j]) {",
            "            arr[k++] = leftHalf[i++];   // left element is smaller (or equal)",
            "        } else {",
            "            arr[k++] = rightHalf[j++];  // right element is smaller",
            "        }",
            "    }",
            "",
            "    // One half may have leftover elements — copy them directly into arr",
            "    while (i < leftHalf.length)  arr[k++] = leftHalf[i++];",
            "    while (j < rightHalf.length) arr[k++] = rightHalf[j++];",
            "}"
        ));
        CODE_MAP.put("Quick Sort", lines(
            "// ─── QUICK SORT ──────────────────────────────────────────────────",
            "// Also 'divide and conquer'. We pick one element as the PIVOT, then",
            "// rearrange (partition) the array so that:",
            "//   - Everything LESS THAN or EQUAL TO the pivot is on its LEFT.",
            "//   - Everything GREATER THAN the pivot is on its RIGHT.",
            "// The pivot is now in its FINAL sorted position.",
            "// Then we recursively sort the left and right sub-arrays.",
            "//",
            "// Average case O(n log n), but worst case O(n^2) if the pivot is always",
            "// the smallest or largest element. Choosing the last element as pivot",
            "// (Lomuto scheme, used here) is simple but not always ideal.",
            "// ─────────────────────────────────────────────────────────────────",
            "public void quickSort(int[] arr, int low, int high) {",
            "",
            "    // Base case: a range of 0 or 1 element is already sorted",
            "    if (low >= high) return;",
            "",
            "    // Partition the array and get back the pivot's final index",
            "    int pivotIndex = partition(arr, low, high);",
            "",
            "    quickSort(arr, low, pivotIndex - 1);   // sort everything LEFT of the pivot",
            "    quickSort(arr, pivotIndex + 1, high);  // sort everything RIGHT of the pivot",
            "}",
            "",
            "// ── Helper: Partition arr[low..high] around the pivot (arr[high]) ─",
            "// After this method returns, arr[pivotIndex] is in its final sorted",
            "// position, with smaller elements to its left and larger to its right.",
            "private int partition(int[] arr, int low, int high) {",
            "",
            "    int pivot      = arr[high];  // we always use the LAST element as the pivot",
            "    int smallerTail = low - 1;  // index of the rightmost element that is <= pivot",
            "                                // starts just before the range (nothing placed yet)",
            "",
            "    // Walk through the array from 'low' to just before 'high'",
            "    for (int j = low; j < high; j++) {",
            "",
            "        if (arr[j] <= pivot) {",
            "            // arr[j] belongs in the 'less than or equal' partition.",
            "            // Expand that partition by one and swap arr[j] into it.",
            "            smallerTail++;",
            "            if (smallerTail != j) {  // only swap if the positions are different",
            "                int temp         = arr[smallerTail];",
            "                arr[smallerTail] = arr[j];",
            "                arr[j]           = temp;",
            "            }",
            "        }",
            "        // If arr[j] > pivot, it already belongs on the right — do nothing",
            "    }",
            "",
            "    // Place the pivot between the two partitions.",
            "    // smallerTail+1 is now the pivot's final sorted position.",
            "    int temp                 = arr[smallerTail + 1];",
            "    arr[smallerTail + 1]     = arr[high];  // pivot moves to its final spot",
            "    arr[high]                = temp;",
            "",
            "    return smallerTail + 1;  // return the pivot's locked-in index",
            "}"
        ));
        CODE_MAP.put("Heap Sort", lines(
            "// ─── HEAP SORT ───────────────────────────────────────────────────",
            "// Uses a data structure called a MAX-HEAP — a tree where every parent",
            "// is GREATER THAN or equal to its children. The largest element always",
            "// sits at the root (index 0).",
            "//",
            "// The array itself is treated as a heap using this index rule:",
            "//   Parent of index i  →  (i - 1) / 2",
            "//   Left child of i    →  2 * i + 1",
            "//   Right child of i   →  2 * i + 2",
            "//",
            "// Phase 1 — BUILD: Turn the array into a valid max-heap.",
            "// Phase 2 — EXTRACT: Repeatedly swap the root (max) to the end,",
            "//           shrink the heap boundary, and restore the heap property.",
            "//",
            "// Guaranteed O(n log n), uses O(1) extra space (sorts IN PLACE).",
            "// ─────────────────────────────────────────────────────────────────",
            "public void heapSort(int[] arr) {",
            "",
            "    int n = arr.length;",
            "",
            "    // ── Phase 1: Build a max-heap from the array ──────────────────",
            "    // We only need to heapify the INTERNAL nodes (those with children).",
            "    // The last internal node is at index (n/2 - 1).",
            "    // We go from bottom to top so each heapify call's subtree is already valid.",
            "    for (int i = n / 2 - 1; i >= 0; i--) {",
            "        heapify(arr, n, i);",
            "    }",
            "",
            "    // ── Phase 2: Extract elements from the heap one by one ────────",
            "    for (int i = n - 1; i > 0; i--) {",
            "",
            "        // The root (arr[0]) is always the largest element in the current heap.",
            "        // Swap it to the end of the unsorted region — it's now in its final place.",
            "        int temp = arr[0];",
            "        arr[0]   = arr[i];",
            "        arr[i]   = temp;",
            "",
            "        // arr[i..n-1] is now fully sorted and locked.",
            "        // Restore the heap property for the remaining unsorted region arr[0..i-1].",
            "        heapify(arr, i, 0);",
            "    }",
            "}",
            "",
            "// ── Helper: Sift element at 'rootIndex' DOWN to restore max-heap ─",
            "// We compare the root with its left and right children.",
            "// If a child is larger, we swap the root with that child, then",
            "// recursively fix the subtree below the swapped child.",
            "//",
            "// 'heapSize' is the boundary — we never touch elements at or beyond it",
            "// (those are already sorted).",
            "private void heapify(int[] arr, int heapSize, int rootIndex) {",
            "",
            "    int largest    = rootIndex;          // assume the root is largest for now",
            "    int leftChild  = 2 * rootIndex + 1;  // index of the left child",
            "    int rightChild = 2 * rootIndex + 2;  // index of the right child",
            "",
            "    // Is the left child larger than the current largest?",
            "    if (leftChild < heapSize && arr[leftChild] > arr[largest]) {",
            "        largest = leftChild;",
            "    }",
            "",
            "    // Is the right child larger than the current largest?",
            "    if (rightChild < heapSize && arr[rightChild] > arr[largest]) {",
            "        largest = rightChild;",
            "    }",
            "",
            "    // If the root isn't the largest, swap it down and keep fixing",
            "    if (largest != rootIndex) {",
            "        int temp         = arr[rootIndex];",
            "        arr[rootIndex]   = arr[largest];",
            "        arr[largest]     = temp;",
            "",
            "        // The subtree rooted at 'largest' may now violate the heap property",
            "        // Recursively fix it",
            "        heapify(arr, heapSize, largest);",
            "    }",
            "}"
        ));
        CODE_MAP.put("Tim Sort", lines(
            "// ─── TIM SORT ────────────────────────────────────────────────────",
            "// Tim Sort is the real-world sorting algorithm used inside Java",
            "// (Arrays.sort for objects) and Python. It's a smart hybrid of",
            "// Insertion Sort and Merge Sort.",
            "//",
            "// Key idea: real-world data often has naturally ordered sequences",
            "// (called 'runs'). Tim Sort exploits this:",
            "//",
            "//   Phase 1 — Sort small chunks ('runs') using Insertion Sort.",
            "//             Insertion Sort is very fast on small arrays (≤ 32 elements).",
            "//   Phase 2 — Repeatedly merge pairs of sorted runs using Merge Sort,",
            "//             doubling the merge window each pass until the whole array",
            "//             is sorted.",
            "//",
            "// RUN = the size of each small chunk sorted in Phase 1.",
            "// ─────────────────────────────────────────────────────────────────",
            "private static final int RUN = 32;",
            "",
            "public void timSort(int[] arr) {",
            "",
            "    int n = arr.length;",
            "",
            "    // ── Phase 1: Sort every RUN-sized chunk with Insertion Sort ───",
            "    // We slice the array into windows of size RUN and sort each one.",
            "    for (int start = 0; start < n; start += RUN) {",
            "        int end = Math.min(start + RUN - 1, n - 1);  // don't go past array end",
            "        insertionSortRun(arr, start, end);",
            "    }",
            "",
            "    // ── Phase 2: Merge sorted runs, doubling the window each pass ─",
            "    // After Phase 1 each block of size RUN is sorted.",
            "    // Now we merge pairs: [0,RUN) + [RUN,2*RUN), then [0,2*RUN) + [2*RUN,4*RUN), ...",
            "    for (int size = RUN; size < n; size *= 2) {",
            "        for (int left = 0; left < n; left += 2 * size) {",
            "            // Find the midpoint and right boundary of this merge",
            "            int mid   = Math.min(left + size - 1,     n - 1);",
            "            int right = Math.min(left + 2 * size - 1, n - 1);",
            "            if (mid < right) {  // only merge if there are actually two halves",
            "                merge(arr, left, mid, right);",
            "            }",
            "        }",
            "    }",
            "}",
            "",
            "// ── Helper: Insertion Sort on the sub-array arr[left..right] ─────",
            "// Identical to standard Insertion Sort, but constrained to a sub-range.",
            "// 'left' acts as the floor — j never goes below it.",
            "private void insertionSortRun(int[] arr, int left, int right) {",
            "    for (int i = left + 1; i <= right; i++) {",
            "        int key = arr[i];  // element to insert into the sorted region",
            "        int j   = i - 1;",
            "        while (j >= left && arr[j] > key) {",
            "            arr[j + 1] = arr[j];  // shift larger elements right",
            "            j--;",
            "        }",
            "        arr[j + 1] = key;  // drop key into the opened gap",
            "    }",
            "}",
            "",
            "// ── Helper: Merge arr[left..mid] and arr[mid+1..right] ───────────",
            "// Both halves are already sorted. We copy them into temporary arrays,",
            "// then write back the elements in the correct merged order.",
            "private void merge(int[] arr, int left, int mid, int right) {",
            "    int[] leftHalf  = Arrays.copyOfRange(arr, left,    mid + 1);",
            "    int[] rightHalf = Arrays.copyOfRange(arr, mid + 1, right + 1);",
            "    int i = 0, j = 0, k = left;",
            "    // Pick the smaller front element from each half and write it back",
            "    while (i < leftHalf.length && j < rightHalf.length) {",
            "        arr[k++] = leftHalf[i] <= rightHalf[j] ? leftHalf[i++] : rightHalf[j++];",
            "    }",
            "    while (i < leftHalf.length)  arr[k++] = leftHalf[i++];   // copy leftovers",
            "    while (j < rightHalf.length) arr[k++] = rightHalf[j++];  // copy leftovers",
            "}"
        ));
        CODE_MAP.put("Radix Sort", lines(
            "// ─── RADIX SORT ──────────────────────────────────────────────────",
            "// Unlike comparison-based sorts (which ask 'is A > B?'), Radix Sort",
            "// sorts numbers DIGIT BY DIGIT, starting from the least significant",
            "// digit (the 1s place) and working up to the most significant digit.",
            "//",
            "// Example: sorting [170, 45, 75, 90, 802, 24, 2, 66]",
            "//   Pass 1 (1s digit): [170, 90, 802, 2, 24, 45, 75, 66]",
            "//   Pass 2 (10s digit): [802, 2, 24, 45, 66, 170, 75, 90]",
            "//   Pass 3 (100s digit): [2, 24, 45, 66, 75, 90, 170, 802]  ← sorted!",
            "//",
            "// Each pass uses a STABLE COUNTING SORT so that relative order is",
            "// preserved for elements with the same digit.",
            "//",
            "// Only works on NON-NEGATIVE integers.",
            "// ─────────────────────────────────────────────────────────────────",
            "public void radixSort(int[] arr) {",
            "",
            "    // Find the maximum value — determines how many digit passes we need",
            "    int max = 0;",
            "    for (int value : arr) {",
            "        if (value > max) max = value;",
            "    }",
            "",
            "    // 'exp' represents the current digit position:",
            "    //   exp=1   → 1s place",
            "    //   exp=10  → 10s place",
            "    //   exp=100 → 100s place, etc.",
            "    // We continue as long as (max / exp) > 0, meaning there are still",
            "    // digits left to process.",
            "    for (int exp = 1; max / exp > 0; exp *= 10) {",
            "        countingSortByDigit(arr, exp);",
            "    }",
            "}",
            "",
            "// ── Helper: Stable sort the array by the digit at position 'exp' ─",
            "// This is a Counting Sort keyed on one digit (0–9) at a time.",
            "// 'Stable' means equal elements keep their original relative order,",
            "// which is essential for Radix Sort to work correctly.",
            "private void countingSortByDigit(int[] arr, int exp) {",
            "",
            "    int   n      = arr.length;",
            "    int[] output = new int[n];   // temporary array to hold the sorted result",
            "    int[] counts = new int[10];  // one counter per digit (0 through 9)",
            "",
            "    // Step 1: Count how many elements have each digit value at position 'exp'",
            "    for (int value : arr) {",
            "        int digit = (value / exp) % 10;  // extract the digit at this position",
            "        counts[digit]++;",
            "    }",
            "",
            "    // Step 2: Convert counts into cumulative end positions.",
            "    // After this, counts[d] tells us the last index in 'output'",
            "    // where a number with digit d can be placed.",
            "    for (int i = 1; i < 10; i++) {",
            "        counts[i] += counts[i - 1];",
            "    }",
            "",
            "    // Step 3: Place each element into its correct position in 'output'.",
            "    // We traverse RIGHT TO LEFT to maintain stability — elements that",
            "    // appeared later in the original array go into the later slot.",
            "    for (int i = n - 1; i >= 0; i--) {",
            "        int digit = (arr[i] / exp) % 10;",
            "        output[--counts[digit]] = arr[i];  // decrement then use as index",
            "    }",
            "",
            "    // Step 4: Copy the sorted result back into the original array",
            "    System.arraycopy(output, 0, arr, 0, n);",
            "}"
        ));
        CODE_MAP.put("Bogo Sort", lines(
            "// ─── BOGO SORT ───────────────────────────────────────────────────",
            "// The world's worst sorting algorithm — included purely as a joke",
            "// and a lesson in what NOT to do.",
            "//",
            "// Algorithm:",
            "//   1. Check if the array is sorted.",
            "//   2. If not, randomly shuffle all the elements and try again.",
            "//   3. Repeat until you get lucky.",
            "//",
            "// Average case: O((n+1)!) — that's factorial time.",
            "// For n=10 elements, the expected number of shuffles is ~3.6 million.",
            "// For n=20 elements... don't even think about it.",
            "//",
            "// NOTE: this visualizer limits Bogo Sort to 6 elements for safety.",
            "// ─────────────────────────────────────────────────────────────────",
            "public void bogoSort(int[] arr) {",
            "",
            "    Random random = new Random();",
            "",
            "    // Keep shuffling until we accidentally land on a sorted arrangement",
            "    while (!isSorted(arr)) {",
            "        shuffle(arr, random);",
            "    }",
            "    // When we finally exit, arr is sorted — purely by luck!",
            "}",
            "",
            "// ── Helper: Check whether the array is in non-decreasing order ───",
            "// Walk through adjacent pairs — if any pair is out of order, return false.",
            "private boolean isSorted(int[] arr) {",
            "    for (int i = 0; i < arr.length - 1; i++) {",
            "        if (arr[i] > arr[i + 1]) {",
            "            return false;  // found a pair in the wrong order",
            "        }",
            "    }",
            "    return true;  // no out-of-order pairs found — it's sorted!",
            "}",
            "",
            "// ── Helper: Fisher-Yates shuffle ──────────────────────────────────",
            "// Produces a uniformly random permutation in O(n) time.",
            "// For each position i (from the end to the start), pick a random",
            "// position j at or before i and swap arr[i] with arr[j].",
            "private void shuffle(int[] arr, Random random) {",
            "    for (int i = arr.length - 1; i > 0; i--) {",
            "        int j    = random.nextInt(i + 1);  // random index in [0, i]",
            "        int temp = arr[i];",
            "        arr[i]   = arr[j];",
            "        arr[j]   = temp;",
            "    }",
            "}"
        ));

        addProfile("Linear Search", "O(n)", "O(1)");
        addProfile("Binary Search", "O(log n)", "O(1)");
        addProfile("Ternary Search", "O(log3 n)", "O(1)");
        addProfile("Jump Search", "O(sqrt n)", "O(1)");
        addProfile("Interpolation Search", "O(log log n) average", "O(1)");
        addProfile("Exponential Search", "O(log n)", "O(1)");
        addProfile("Fibonacci Search", "O(log n)", "O(1)");
        addProfile("Breadth-First Search", "O(V + E)", "O(V)");
        addProfile("Depth-First Search", "O(V + E)", "O(V)");
        addProfile("KMP Search", "O(n + m)", "O(m)");
        addProfile("Rabin-Karp Search", "O(n + m) average", "O(1)");
        addProfile("Bubble Sort", "best O(n), average O(n^2), worst O(n^2)", "O(1)");
        addProfile("Insertion Sort", "best O(n), average O(n^2), worst O(n^2)", "O(1)");
        addProfile("Selection Sort", "O(n^2)", "O(1)");
        addProfile("Gnome Sort", "best O(n), average O(n^2), worst O(n^2)", "O(1)");
        addProfile("Merge Sort", "O(n log n)", "O(n)");
        addProfile("Quick Sort", "average O(n log n), worst O(n^2)", "O(log n)");
        addProfile("Heap Sort", "O(n log n)", "O(1)");
        addProfile("Tim Sort", "best O(n), average O(n log n), worst O(n log n)", "O(n)");
        addProfile("Radix Sort", "O(nk)", "O(n + k)");
        addProfile("Bogo Sort", "average O((n+1)!)", "O(1)");

        APP_DATA.add(new String[]{
            "Linear Search", "O(n)", "O(1)", "Small or unsorted data",
            "Scanning inventory, searching short logs, checking basic lists",
            "It works without any sorting or indexing."
        });
        APP_DATA.add(new String[]{
            "Binary Search", "O(log n)", "O(1)", "Large sorted arrays",
            "Dictionary lookups, sorted database indexes, static leaderboards",
            "Extremely fast once the data is sorted."
        });
        APP_DATA.add(new String[]{
            "Ternary Search", "O(log3 n)", "O(1)", "Specialized discrete searches",
            "Unimodal optimization problems, academic comparisons with Binary Search",
            "Usually less practical than Binary Search on arrays."
        });
        APP_DATA.add(new String[]{
            "Jump Search", "O(sqrt n)", "O(1)", "Block-oriented sorted data",
            "Sequential storage, page-based scans, systems with expensive random seeks",
            "Useful when jumping in chunks is cheaper than full random access."
        });
        APP_DATA.add(new String[]{
            "Interpolation Search", "O(log log n) average", "O(1)", "Uniformly distributed numeric data",
            "Phone directories, evenly spaced IDs, dense numeric lookup tables",
            "Fast on uniform data but can degrade badly on skewed input."
        });
        APP_DATA.add(new String[]{
            "Exponential Search", "O(log n)", "O(1)", "Unknown-size sorted data",
            "Unbounded streams, iterators over sorted files, range discovery before binary search",
            "It finds the window first, then applies Binary Search."
        });
        APP_DATA.add(new String[]{
            "Fibonacci Search", "O(log n)", "O(1)", "Systems that avoid division",
            "Embedded devices, older architectures, teaching alternative divide strategies",
            "It navigates the array with Fibonacci offsets instead of midpoint division."
        });
        APP_DATA.add(new String[]{
            "Breadth-First Search", "O(V + E)", "O(V)", "Shortest path in unweighted graphs",
            "Social graph hops, routing on unweighted maps, crawler frontier expansion",
            "BFS guarantees the shortest unweighted path."
        });
        APP_DATA.add(new String[]{
            "Depth-First Search", "O(V + E)", "O(V)", "Deep traversal and backtracking",
            "Cycle detection, dependency walks, maze solving, topological workflows",
            "DFS uses less memory on wide graphs but does not guarantee shortest paths."
        });
        APP_DATA.add(new String[]{
            "KMP Search", "O(n + m)", "O(m)", "Single-pattern text search",
            "Editors, log scanners, DNA sequence matching, content moderation",
            "The LPS table avoids re-checking characters."
        });
        APP_DATA.add(new String[]{
            "Rabin-Karp Search", "O(n + m) average", "O(1)", "Hash-based substring search",
            "Plagiarism checks, multi-pattern filters, rolling-hash pipelines",
            "Hash collisions require a direct verification step."
        });
        APP_DATA.add(new String[]{
            "Bubble Sort", "O(n^2)", "O(1)", "Teaching and tiny arrays",
            "Intro CS demos, simple visualizers, swap-heavy animation examples",
            "Easy to explain, but rarely a production choice."
        });
        APP_DATA.add(new String[]{
            "Insertion Sort", "O(n^2)", "O(1)", "Small or nearly sorted arrays",
            "Hybrid sort base cases, incremental maintenance of ordered data",
            "Excellent on tiny inputs and already-ordered data."
        });
        APP_DATA.add(new String[]{
            "Selection Sort", "O(n^2)", "O(1)", "Low-write environments",
            "Memory-constrained demos, cases where swaps are more expensive than comparisons",
            "It minimizes swaps but still pays quadratic comparison cost."
        });
        APP_DATA.add(new String[]{
            "Gnome Sort", "O(n^2)", "O(1)", "Educational comparisons",
            "Visual explanations of local swap behavior and backtracking",
            "Mostly used because it is simple and visually distinctive."
        });
        APP_DATA.add(new String[]{
            "Merge Sort", "O(n log n)", "O(n)", "Stable large-scale sorting",
            "Linked-list sorting, external sorting, stable batch processing",
            "Predictable performance and stability are its main strengths."
        });
        APP_DATA.add(new String[]{
            "Quick Sort", "O(n log n) average", "O(log n)", "Fast in-memory sorting",
            "General-purpose array sorting, partition-based divide and conquer",
            "Very fast in practice, but pivot choice matters."
        });
        APP_DATA.add(new String[]{
            "Heap Sort", "O(n log n)", "O(1)", "Guaranteed in-place sorting",
            "Systems that need bounded memory with reliable worst-case performance",
            "It trades cache-friendliness for strict memory usage."
        });
        APP_DATA.add(new String[]{
            "Tim Sort", "O(n log n)", "O(n)", "Real-world application sorting",
            "Java and Python runtime sorting, partially ordered business data",
            "It exploits existing runs and is used in production runtimes."
        });
        APP_DATA.add(new String[]{
            "Radix Sort", "O(nk)", "O(n + k)", "Integer-heavy non-comparison sorting",
            "Sorting IDs, ZIP codes, bounded integers, fixed-width numeric keys",
            "It is fast when the key width is limited and values are non-negative."
        });
        APP_DATA.add(new String[]{
            "Bogo Sort", "O((n+1)!)", "O(1)", "Cautionary examples only",
            "Comedy demos, impossibility lessons, worst-case algorithm discussions",
            "This exists to show what not to do."
        });
    }

    static String getTimeComplexity(String algorithm) {
        return TIME_MAP.getOrDefault(algorithm, "-");
    }

    static String getSpaceComplexity(String algorithm) {
        return SPACE_MAP.getOrDefault(algorithm, "-");
    }

    private static void addProfile(String algorithm, String time, String space) {
        TIME_MAP.put(algorithm, time);
        SPACE_MAP.put(algorithm, space);
    }

    private static String lines(String... lines) {
        return String.join("\n", lines);
    }
}